import { useEffect, useMemo, useRef, useState } from "react";
import { api } from "../../api";
import { useMarketStream } from "./useMarketStream";
import type { OrderTicket, Quote, TerminalPosition, TerminalTab, Timeframe } from "./types";
import TradingChart from "./TradingChart";
import { useTerminalStore } from "./store";

const QUOTES: Quote[] = [
  { symbol: "NIFTY", name: "Nifty 50", price: 24672.35, change: 126.8, changePercent: .52, volume: 1842390, atr: 186, trendScore: 82, aiScore: 88, signal: "Strong buy", favorite: true },
  { symbol: "BANKNIFTY", name: "Nifty Bank", price: 55342.1, change: -134.7, changePercent: -.24, volume: 930202, atr: 421, trendScore: 48, aiScore: 61, signal: "Neutral", favorite: true },
  { symbol: "RELIANCE", name: "Reliance", price: 1487.5, change: 16.2, changePercent: 1.1, volume: 5941020, atr: 29.4, trendScore: 78, aiScore: 81, signal: "Buy" },
  { symbol: "HDFCBANK", name: "HDFC Bank", price: 1981.8, change: -11.3, changePercent: -.57, volume: 3211904, atr: 32.8, trendScore: 36, aiScore: 47, signal: "Sell" },
];
const tabs: { id: TerminalTab; label: string }[] = [{ id: "positions", label: "Positions" }, { id: "orders", label: "Orders" }, { id: "history", label: "Trade history" }, { id: "journal", label: "Journal" }, { id: "alerts", label: "Alerts" }, { id: "logs", label: "Strategy logs" }];
const frames: Timeframe[] = ["1m", "5m", "15m", "1h", "4h", "1D"];
const money = (value: number) => new Intl.NumberFormat("en-IN", { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value);
const initial: OrderTicket = { symbol: "NIFTY", side: "BUY", type: "MARKET", quantity: 65, stopLoss: 24600, target: 24820, trailingStopPercent: .5, riskPercent: 1, bracketOrder: true };
type Activity = { id: string; time: string; event: string; detail: string; tone?: "positive" | "negative" };

export default function TerminalWorkspace() {
  const symbol = useTerminalStore((state) => state.symbol), setSymbol = useTerminalStore((state) => state.setSymbol), timeframe = useTerminalStore((state) => state.timeframe), setTimeframe = useTerminalStore((state) => state.setTimeframe), tab = useTerminalStore((state) => state.activeTab), setTab = useTerminalStore((state) => state.setActiveTab), activeDrawing = useTerminalStore((state) => state.activeDrawing), setActiveDrawing = useTerminalStore((state) => state.setActiveDrawing);
  const [ticket, setTicket] = useState(initial), [query, setQuery] = useState(""), [notice, setNotice] = useState<string | null>(null), [submitting, setSubmitting] = useState(false), [commandOpen, setCommandOpen] = useState(false);
  const [activity, setActivity] = useState<Activity[]>([{ id: "market-open", time: "09:15:02", event: "Market data connected", detail: "NSE cash and derivatives feed is live.", tone: "positive" }, { id: "risk", time: "09:18:44", event: "Risk check passed", detail: "Portfolio exposure is within the intraday limit." }]);
  const searchRef = useRef<HTMLInputElement>(null);
  const stream = useMarketStream(symbol);
  const quote = QUOTES.find((item) => item.symbol === symbol) ?? QUOTES[0];
  const filtered = useMemo(() => QUOTES.filter((item) => `${item.symbol} ${item.name}`.toLowerCase().includes(query.toLowerCase())), [query]);
  const position: TerminalPosition = { id: "paper-1", symbol: "NIFTY", product: "MIS", side: "BUY", quantity: 65, averagePrice: 24611.4, lastPrice: quote.price, pnl: (quote.price - 24611.4) * 65, pnlPercent: ((quote.price / 24611.4) - 1) * 100, stopLoss: ticket.stopLoss, target: ticket.target };
  useEffect(() => setTicket((current) => ({ ...current, symbol, price: quote.price })), [symbol, quote.price]);
  useEffect(() => { const shortcuts = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === "k") { event.preventDefault(); setCommandOpen(true); window.setTimeout(() => searchRef.current?.focus(), 0); return; } if ((event.target as HTMLElement)?.matches("input,select,textarea")) return; if (event.key.toLowerCase() === "b") setTicket((v) => ({ ...v, side: "BUY" })); if (event.key.toLowerCase() === "s") setTicket((v) => ({ ...v, side: "SELL" })); if (event.key.toLowerCase() === "p") setTab("positions"); if (event.key === "Escape") setCommandOpen(false); }; window.addEventListener("keydown", shortcuts); return () => window.removeEventListener("keydown", shortcuts); }, []);
  const change = <K extends keyof OrderTicket>(key: K, value: OrderTicket[K]) => setTicket((current) => ({ ...current, [key]: value }));
  const submit = async () => { setSubmitting(true); setNotice(null); try { await api.executeOrder({ strategy_name: "terminal_manual", symbol: ticket.symbol, side: ticket.side, entry_price: ticket.type === "MARKET" ? quote.price : ticket.price, stop_loss: ticket.stopLoss, target_price: ticket.target, trailing_stop_pct: ticket.trailingStopPercent, signal_time: new Date().toISOString(), metadata: { quantity: ticket.quantity, order_type: ticket.type, bracket_order: ticket.bracketOrder, source: "trading-terminal" } }); setNotice(`${ticket.side} order submitted to the paper execution queue.`); setActivity((items) => [{ id: `order-${Date.now()}`, time: new Date().toLocaleTimeString([], { hour: "2-digit", minute: "2-digit", second: "2-digit" }), event: `${ticket.side} ${ticket.symbol} submitted`, detail: `${ticket.quantity} units · ${ticket.type} · paper execution queue`, tone: ticket.side === "BUY" ? "positive" : "negative" }, ...items]); setTab("orders"); } catch (error: any) { setNotice(error?.response?.data?.detail ?? "Order could not be submitted. Check the execution service."); } finally { setSubmitting(false); } };
  return <section className="terminal" aria-label="QuantGrid trading terminal">
    <header className="terminal-commandbar"><div><span className="terminal-kicker">Trading terminal · NSE</span><strong>{quote.name} <em>{money(quote.price)}</em></strong><span className={quote.change >= 0 ? "positive" : "negative"}>{quote.change >= 0 ? "+" : ""}{money(quote.change)} ({quote.changePercent.toFixed(2)}%)</span></div><div><span className={`stream-state ${stream}`}>{stream === "live" ? "Live stream" : stream === "connecting" ? "Connecting" : "Reconnecting"}</span><button className="terminal-icon-button" type="button" aria-label="Open command palette" onClick={() => setCommandOpen(true)}>⌘ K</button></div></header>
    <section className="terminal-market-strip" aria-label="Market pulse"><span><small>NIFTY 50</small><b className="positive">24,672.35 <i>+0.52%</i></b></span><span><small>BANK NIFTY</small><b className="negative">55,342.10 <i>−0.24%</i></b></span><span><small>SENSEX</small><b className="positive">80,490.12 <i>+0.31%</i></b></span><span><small>INDIA VIX</small><b>12.84 <i className="negative">+1.08%</i></b></span><span><small>Market breadth</small><b>31 / 19 <i>adv / dec</i></b></span></section>
    {commandOpen && <div className="terminal-command-palette" role="dialog" aria-modal="true" aria-label="Command palette"><button className="terminal-command-backdrop" aria-label="Close command palette" onClick={() => setCommandOpen(false)} /><div className="terminal-command-dialog"><span className="terminal-kicker">Jump to instrument</span><input ref={searchRef} value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search NIFTY, BANKNIFTY, RELIANCE…" aria-label="Search instruments" />{filtered.map((item) => <button key={item.symbol} type="button" onClick={() => { setSymbol(item.symbol); setQuery(""); setCommandOpen(false); }}><span><b>{item.symbol}</b><small>{item.name}</small></span><strong className={item.change >= 0 ? "positive" : "negative"}>{money(item.price)} · {item.changePercent.toFixed(2)}%</strong></button>)}</div></div>}
    <div className="terminal-grid"><aside className="terminal-left"><section className="terminal-panel watchlist-panel"><div className="panel-title"><h2>Watchlist</h2><button type="button" aria-label="Add instrument">＋</button></div><input className="terminal-search" aria-label="Search watchlist" placeholder="Search instruments" value={query} onChange={(e) => setQuery(e.target.value)} /><div className="watchlist-header"><span>Instrument</span><span>Last</span><span>Chg%</span></div>{filtered.map((item) => <button type="button" className={`watch-row ${item.symbol === symbol ? "selected" : ""}`} onClick={() => setSymbol(item.symbol)} key={item.symbol}><span><b>{item.favorite ? "★ " : ""}{item.symbol}</b><small>{item.signal} · AI {item.aiScore}</small></span><strong>{money(item.price)}</strong><i className={item.change >= 0 ? "positive" : "negative"}>{item.changePercent.toFixed(2)}%</i></button>)}</section><MiniPanels /></aside>
      <main className="terminal-center"><section className="terminal-panel chart-shell"><div className="chart-toolbar"><div className="timeframe-group">{frames.map((item) => <button type="button" className={item === timeframe ? "active" : ""} onClick={() => setTimeframe(item)} key={item}>{item}</button>)}</div><div className="chart-actions"><button type="button">Indicators</button><button type="button">Drawings</button><button type="button">⚙</button></div></div><div className="chart-annotations"><span>EMA 20</span><span>VWAP</span><span>Market structure</span><span>Volume</span></div><TradingChart symbol={symbol} timeframe={timeframe} support={24540} resistance={24790} /><div className="drawing-rail">{([['cursor','⌖','Cursor'],['trendline','╱','Trendline'],['horizontal','━','Horizontal line'],['rectangle','□','Rectangle'],['fib','ƒ','Fib retracement'],['riskReward','R','Risk reward']] as const).map(([tool, icon, label]) => <button className={activeDrawing === tool ? "active" : ""} type="button" title={label} aria-label={label} onClick={() => setActiveDrawing(tool)} key={tool}>{icon}</button>)}</div></section><AiPanel score={quote.aiScore} /></main>
      <aside className="terminal-right"><OrderPanel quote={quote} ticket={ticket} change={change} submit={submit} submitting={submitting} notice={notice} /><section className="terminal-panel calculator-panel"><div className="panel-title"><h2>Position size</h2><button type="button">Auto</button></div><p>1% risk on ₹5,00,000 capital</p><strong>{ticket.quantity} <small>units · 1 lot</small></strong><span>Max loss ₹{money(Math.abs(quote.price - ticket.stopLoss) * ticket.quantity)}</span></section></aside></div>
    <section className="terminal-panel terminal-bottom"><div className="bottom-tabs" role="tablist">{tabs.map((item) => <button type="button" role="tab" aria-selected={tab === item.id} className={tab === item.id ? "active" : ""} onClick={() => setTab(item.id)} key={item.id}>{item.label}{item.id === "positions" && <span>1</span>}</button>)}</div><TerminalDock tab={tab} position={position} activity={activity} /></section>
  </section>;
}

function MiniPanels() { return <><section className="terminal-panel compact-panel"><div className="panel-title"><h2>Market overview</h2><span>India</span></div><div className="market-mini"><span>NIFTY <b className="positive">+0.52%</b></span><span>BANK <b className="negative">−0.24%</b></span><span>VIX <b>12.84</b></span></div></section><section className="terminal-panel compact-panel"><div className="panel-title"><h2>Sector performance</h2><span>1D</span></div>{["IT", "Auto", "Financials", "Energy"].map((sector, index) => <div className="sector-row" key={sector}><span>{sector}</span><div><i style={{ width: `${78 - index * 16}%` }} /></div><b className={index === 3 ? "negative" : "positive"}>{index === 3 ? "−0.28%" : `+${(1.42 - index * .3).toFixed(2)}%`}</b></div>)}</section></>; }
function AiPanel({ score }: { score: number }) { return <section className="terminal-panel ai-panel"><div className="panel-title"><div><span className="terminal-kicker">QuantGrid AI</span><h2>Trade intelligence</h2></div><span className="ai-score">{score}<small>/100</small></span></div><div className="ai-metrics">{[["Trend probability", "72%"], ["Momentum", "84/100"], ["Volume", "68/100"], ["Institutional", "Accumulating"]].map(([label, value]) => <span key={label}><small>{label}</small><b>{value}</b></span>)}</div><p>Long bias above 24,620. Suggested entry near VWAP; protective stop below 24,590 with a 1:2.1 risk/reward profile.</p></section>; }
function OrderPanel({ quote, ticket, change, submit, submitting, notice }: { quote: Quote; ticket: OrderTicket; change: <K extends keyof OrderTicket>(key: K, value: OrderTicket[K]) => void; submit: () => Promise<void>; submitting: boolean; notice: string | null }) { const risk = Math.abs(quote.price - ticket.stopLoss) * ticket.quantity; const reward = Math.abs(ticket.target - quote.price) / Math.max(Math.abs(quote.price - ticket.stopLoss), 1); return <section className="terminal-panel order-panel"><div className="panel-title"><h2>Order entry</h2><span className="paper-badge">Paper</span></div><div className="side-toggle"><button type="button" className={ticket.side === "BUY" ? "buy active" : "buy"} onClick={() => change("side", "BUY")}>Buy <kbd>B</kbd></button><button type="button" className={ticket.side === "SELL" ? "sell active" : "sell"} onClick={() => change("side", "SELL")}>Sell <kbd>S</kbd></button></div><div className="order-types">{(["MARKET", "LIMIT", "SL"] as const).map((type) => <button type="button" className={ticket.type === type ? "active" : ""} onClick={() => change("type", type)} key={type}>{type}</button>)}</div><label>Quantity<input type="number" min="1" value={ticket.quantity} onChange={(e) => change("quantity", Number(e.target.value))} /></label>{ticket.type !== "MARKET" && <label>Limit price<input type="number" value={ticket.price ?? quote.price} onChange={(e) => change("price", Number(e.target.value))} /></label>}<div className="ticket-grid"><label>Stop loss<input type="number" value={ticket.stopLoss} onChange={(e) => change("stopLoss", Number(e.target.value))} /></label><label>Target<input type="number" value={ticket.target} onChange={(e) => change("target", Number(e.target.value))} /></label><label>Trail %<input type="number" step=".1" value={ticket.trailingStopPercent ?? ""} onChange={(e) => change("trailingStopPercent", Number(e.target.value))} /></label><label>Risk %<input type="number" step=".25" value={ticket.riskPercent} onChange={(e) => change("riskPercent", Number(e.target.value))} /></label></div><label className="checkline"><input type="checkbox" checked={ticket.bracketOrder} onChange={(e) => change("bracketOrder", e.target.checked)} /> Bracket order (SL + target)</label><div className="order-summary-grid"><span><small>Margin</small><b>₹{money(ticket.quantity * quote.price * .18)}</b></span><span><small>Risk</small><b>₹{money(risk)}</b></span><span><small>R:R</small><b>1:{reward.toFixed(1)}</b></span></div><button type="button" className={`place-order ${ticket.side.toLowerCase()}`} disabled={submitting} onClick={() => void submit()}>{submitting ? "Submitting…" : `${ticket.side === "BUY" ? "Buy" : "Sell"} ${ticket.symbol}`}</button>{notice && <p role="status" className="order-notice">{notice}</p>}</section>; }
function PositionTable({ position }: { position: TerminalPosition }) { return <div className="terminal-table-wrap"><table><thead><tr><th>Instrument</th><th>Product</th><th>Qty</th><th>Avg. price</th><th>LTP</th><th>SL / Target</th><th>P&L</th><th>Actions</th></tr></thead><tbody><tr><td><b>{position.symbol}</b><small>{position.side} · Intraday</small></td><td>{position.product}</td><td>{position.quantity}</td><td>{money(position.averagePrice)}</td><td>{money(position.lastPrice)}</td><td>{money(position.stopLoss)} / {money(position.target)}</td><td className={position.pnl >= 0 ? "positive" : "negative"}><b>₹{money(position.pnl)}</b><small>{position.pnlPercent.toFixed(2)}%</small></td><td><button type="button">Exit</button><button type="button">Trail</button></td></tr></tbody></table></div>; }
function TerminalDock({ tab, position, activity }: { tab: TerminalTab; position: TerminalPosition; activity: Activity[] }) { if (tab === "positions") return <PositionTable position={position} />; if (tab === "orders") { const orders = activity.filter((item) => item.id.startsWith("order-")); return <div className="terminal-activity-list">{orders.length ? orders.map((item) => <ActivityRow item={item} key={item.id} />) : <EmptyDock title="No orders in this session" detail="New orders appear here immediately after submission." />}</div>; } if (tab === "alerts" || tab === "logs") return <div className="terminal-activity-list">{activity.map((item) => <ActivityRow item={item} key={item.id} />)}</div>; if (tab === "history") return <EmptyDock title="No completed trades today" detail="Executed and closed orders will be retained in your trade history." />; return <EmptyDock title="Your trading journal is ready" detail="Add notes against completed trades from the history workspace." />; }
function ActivityRow({ item }: { item: Activity }) { return <article className="terminal-activity-row"><time>{item.time}</time><span className={`activity-pip ${item.tone ?? ""}`} /><div><b>{item.event}</b><small>{item.detail}</small></div><button type="button">View</button></article>; }
function EmptyDock({ title, detail }: { title: string; detail: string }) { return <div className="tab-empty"><strong>{title}</strong><span>{detail}</span></div>; }
