from datetime import datetime
from pathlib import Path
from collections import defaultdict

SEVERITY_SCORE = {
    "HIGH": 10,
    "MEDIUM": 5,
    "LOW": 2,
}


def calculate_risk_score(findings):
    score = sum(
        SEVERITY_SCORE.get(f.get("severity", "LOW"), 1)
        for f in findings
    )
    return min(score, 100)


def risk_rating(score):
    if score >= 60:
        return "CRITICAL"
    elif score >= 30:
        return "HIGH"
    elif score >= 15:
        return "MEDIUM"
    return "LOW"


def aggregate_findings(findings):

    grouped = defaultdict(lambda: {
        "id": "",
        "severity": "",
        "issue": "",
        "files": [],
        "count": 0
    })

    for finding in findings:

        key = (
            finding.get("id"),
            finding.get("issue")
        )

        item = grouped[key]

        item["id"] = finding.get("id")
        item["severity"] = finding.get("severity")
        item["issue"] = finding.get("issue")
        item["count"] += 1

        file = finding.get("file")

        if file and file not in item["files"]:
            item["files"].append(file)

    return list(grouped.values())


def recommendation(fid):

    recommendations = {
        "TRADE-001": """
- Add pre-trade validation
- Enforce stop-loss
- Add position sizing
- Add broker circuit breaker
""",

        "CODE-001": """
- Replace bare except blocks
- Catch specific exceptions
- Add structured logging
""",

        "SECURITY-001": """
- Remove hardcoded secrets
- Move secrets into .env
- Use Secret Manager or Vault
""",

        "SECURITY-002": """
- Rotate AWS credentials immediately
- Store keys securely
""",

        "SECURITY-003": """
- Remove eval()
- Replace with safe parsing
""",

        "SECURITY-004": """
- Remove exec()
- Use safer alternatives
"""
    }

    return recommendations.get(
        fid,
        "- Review and fix the identified issue."
    )


def generate_report(report):

    findings = report.get("findings", [])

    grouped = aggregate_findings(findings)

    score = calculate_risk_score(findings)

    rating = risk_rating(score)

    architecture = report.get("architecture", {})

    security = report.get("security", {})

    severity_groups = {
        "HIGH": [],
        "MEDIUM": [],
        "LOW": []
    }

    for item in grouped:
        severity_groups[item["severity"]].append(item)

    content = f"""# QuantGrid AI Audit Report

Generated: {datetime.now():%Y-%m-%d %H:%M:%S}

---

# Executive Summary

Files Scanned: {report.get("files_scanned")}

Total Findings: {len(findings)}

Unique Issues: {len(grouped)}

Risk Score: {score}/100

Risk Rating: **{rating}**

---

# Risk Distribution

| Severity | Count |
|----------|------:|
| HIGH | {len(severity_groups["HIGH"])} |
| MEDIUM | {len(severity_groups["MEDIUM"])} |
| LOW | {len(severity_groups["LOW"])} |

---
"""

    for severity in ["HIGH", "MEDIUM", "LOW"]:

        content += f"\n# {severity.title()} Findings\n"

        if not severity_groups[severity]:
            content += "\nNo findings.\n"
            continue

        for item in severity_groups[severity]:

            content += f"""

## {item["id"]}

Severity: {item["severity"]}

Issue:
{item["issue"]}

Occurrences:
{item["count"]}

Affected Files:
"""

            for f in item["files"]:
                content += f"- {f}\n"

            content += "\nRecommendation:\n"
            content += recommendation(item["id"])
            content += "\n\n---\n"

    content += f"""

# Architecture Assessment

Architecture Score: {architecture.get("score", "N/A")}/100

Agent:
{architecture.get("agent", "")}

Services:
"""

    for service in architecture.get("services", []):
        content += f"- {service}\n"

    content += "\nTechnologies:\n"

    for tech in architecture.get("technologies", []):
        content += f"- {tech}\n"

    content += "\nWarnings:\n"

    for warning in architecture.get("warnings", []):
        content += f"- {warning}\n"

    content += "\nRecommendations:\n"

    for rec in architecture.get("recommendations", []):
        content += f"- {rec}\n"

    content += f"""

---

# Security Assessment

Security Score: {security.get("score", "N/A")}/100

Agent:
{security.get("agent", "")}

Security Findings:
{len(security.get("findings", []))}

---

Report generated by QuantGrid AI Audit Agent.
"""

    output = Path("reports/QuantGrid_AI_Audit_Report.md")
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(content, encoding="utf-8")

    return str(output)