from enum import Enum


class TradeState(str, Enum):
    SIGNAL_GENERATED = "SIGNAL_GENERATED"
    RISK_VALIDATED = "RISK_VALIDATED"

    ORDER_CREATED = "ORDER_CREATED"
    ORDER_SUBMITTED = "ORDER_SUBMITTED"
    ORDER_ACCEPTED = "ORDER_ACCEPTED"
    ORDER_FILLED = "ORDER_FILLED"

    POSITION_OPENED = "POSITION_OPENED"

    TARGET_HIT = "TARGET_HIT"
    STOP_LOSS_HIT = "STOP_LOSS_HIT"
    MANUAL_EXIT = "MANUAL_EXIT"

    POSITION_CLOSED = "POSITION_CLOSED"

    ANALYTICS_COMPLETED = "ANALYTICS_COMPLETED"